site_name: Jaeger Documentation
edit_uri: edit/master/docs/
theme_dir: docs/theme
markdown_extensions:
  - admonition
  - codehilite
  - toc(permalink=true)
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.inlinehilite
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde
site_favicon: 'images/favicon.ico'
repo_name: 'uber/jaeger'
repo_url: 'https://github.com/uber/jaeger'
extra:
  logo: 'images/jaeger-logo.png'
google_analytics:
  - 'UA-97254222-1'
  - 'auto'
pages: 
  - '简介': 'index.md'
  - '上手操作' : 'getting_started.md'
  - '支持的客户端库' : 'client_libraries.md'
  - '系统架构' : 'architecture.md'
  - '部署' : 'deployment.md'
  - '发展路线' : 'roadmap.md'
  - '新闻' : 'news.md'
